# (PART) Appendix {-}

# About the Data {#about-the-data}

## 10X Genomics PBMC Data

The *TENxPBMCData* package provides a Bioconductor resource for representing and manipulating nine different single-cell RNA-seq (scRNA-seq) data sets on peripheral blood mononuclear cells (PBMC) generated by 10X Genomics from various healthy donors. Here we generally make use of the smaller datasets, `pbmc3k` and `pbmc4k`, available via the package. For more information, we refer to the [10X Genomics datasets online resource](https://www.10xgenomics.com/resources/datasets/) (PBMC data is within the Single Cell Gene Expression table).

## Cellbench_data

The 5 cell line scRNA-seq data from the [CellBench_data](https://github.com/LuyiTian/CellBench_data) repository is used in examples where having a cell label is important. In the *CellBench_data* repository, the data is stored within the workspace `data/sincell_with_class_5cl.RData` as `sc_10x_5cl_qc`. We have extracted it and saved it under this book's Github repo within the `_rfiles/_data` folder for ease of use. 

The data arrives as a `SingleCellExperiment` class object, and has already undergone basic preprocessing, including quality control and normalization. The most important aspect to this data - the cell labels pertaining to the 5 cell lines sequenced - can be found within the `colData` component under the column name `cell_line`. 

Note that this data will be made available on Bioconductor via the *scRNAseq* package in the near future.


