```{r, echo=FALSE}
knitr::opts_chunk$set(cache=TRUE, error=FALSE, warning=FALSE, message=FALSE)
```

```{r loading}
library(TENxPBMCData)
pbmcID <- TENxPBMCData('pbmcID')
```

```{r quality-control}
is.mito <- grep("MT", rowData(pbmcID)$Symbol_TENx)

library(scater)
pbmcID <- calculateQCMetrics(pbmcID, feature_controls=list(Mito=is.mito))
high.mito <- isOutlier(pbmcID$pct_counts_Mito, nmads=3, type="higher")
pbmcID <- pbmcID[,!high.mito]
```

```{r normalization}
pbmcID <- normalize(pbmcID)
```

```{r variance-modelling}
library(scran)
fitID <- trendVar(pbmcID, use.spikes = FALSE)
decID <- decomposeVar(pbmcID, fitID)
```

```{r feature-selection}
chosen.hvgs <- which(decID$bio > 0)
```

```{r dimensionality-reduction}
# Using randomized SVD, which is more efficient for 
# file-backed matrices.
set.seed(10000)
pbmcID <- runPCA(pbmcID, feature_set=chosen.hvgs, ncomponents=25,
    BSPARAM=BiocSingular::RandomParam())

set.seed(100000)
pbmcID <- runTSNE(pbmcID, use_dimred="PCA")

set.seed(1000000)
pbmcID <- runUMAP(pbmcID, use_dimred="PCA")
```

```{r clustering}
g <- buildSNNGraph(pbmcID, k=10, use.dimred = 'PCA')
clust <- igraph::cluster_walktrap(g)$membership
pbmcID$cluster <- factor(clust)
```
